services:
  backend:
    build:
      context: .  
      dockerfile: backend/Dockerfile 
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: wolap
      POSTGRES_PASSWORD: wolap
      POSTGRES_DB: articledb
    ports:
      - "5432:5432"


  # Prévision si dockersisation front
  # frontend:
  #   build:
  #     context: ./my_project_frontend
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
